#ifndef DAQSTER_CORE_GLOBAL_H
#define DAQSTER_CORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DAQSTER_CORE_LIBRARY)
#  define DAQSTER_CORE_EXPORT Q_DECL_EXPORT
#else
#  define DAQSTER_CORE_EXPORT Q_DECL_IMPORT
#endif

#endif // DAQSTER_CORE_GLOBAL_H