# FindQtVersion.cmake
# Detects available Qt version and sets appropriate variables

# Debug information
message(STATUS "=== Qt Version Detection Debug ===")
message(STATUS "CMAKE_PREFIX_PATH: ${CMAKE_PREFIX_PATH}")
if(DEFINED USE_QT6)
    message(STATUS "USE_QT6 defined: TRUE, value: ${USE_QT6}")
else()
    message(STATUS "USE_QT6 defined: FALSE")
endif()

# Check for explicit Qt version preference from command line
if(DEFINED USE_QT6)
    if(USE_QT6)
        set(QT_PREFER_QT6 TRUE)
        message(STATUS "Qt6 preference set via USE_QT6=ON")
    else()
        set(QT_PREFER_QT5 TRUE)
        message(STATUS "Qt5 preference set via USE_QT6=OFF")
    endif()
elseif(CMAKE_PREFIX_PATH)
    # Use simple pattern matching for Qt version detection from CMAKE_PREFIX_PATH
    if(CMAKE_PREFIX_PATH MATCHES "qt/5\\.|qt5|Qt/5\\.|Qt5|5\\.15|5\\.14|5\\.13|5\\.12")
        set(QT_PREFER_QT5 TRUE)
        message(STATUS "Qt5 preference detected from CMAKE_PREFIX_PATH: ${CMAKE_PREFIX_PATH}")
    elseif(CMAKE_PREFIX_PATH MATCHES "qt/6\\.|qt6|Qt/6\\.|Qt6|6\\.|6\\.0|6\\.1|6\\.2|6\\.3|6\\.4|6\\.5|6\\.6|6\\.7|6\\.8|6\\.9")
        set(QT_PREFER_QT6 TRUE)
        message(STATUS "Qt6 preference detected from CMAKE_PREFIX_PATH: ${CMAKE_PREFIX_PATH}")
    else()
        message(STATUS "No Qt version preference detected from CMAKE_PREFIX_PATH: ${CMAKE_PREFIX_PATH}")
    endif()
endif()

# Try to find Qt5 first if preference is set, otherwise try Qt6 first
if(QT_PREFER_QT5)
    find_package(Qt5 QUIET COMPONENTS Core Widgets Gui)
    if(Qt5_FOUND)
        set(QT_VERSION_MAJOR 5)
        set(QT_PREFIX Qt5)
        set(QT_FOUND TRUE)
        message(STATUS "Using Qt5 (${Qt5_VERSION}) - preferred")
    else()
        # Fallback to Qt6
        find_package(Qt6 QUIET COMPONENTS Core Widgets Gui)
        if(Qt6_FOUND)
            set(QT_VERSION_MAJOR 6)
            set(QT_PREFIX Qt6)
            set(QT_FOUND TRUE)
            message(STATUS "Using Qt6 (${Qt6_VERSION}) - fallback")
        endif()
    endif()
else()
    # Try to find Qt6 first (default behavior)
    find_package(Qt6 QUIET COMPONENTS Core Widgets Gui)
    if(Qt6_FOUND)
        set(QT_VERSION_MAJOR 6)
        set(QT_PREFIX Qt6)
        set(QT_FOUND TRUE)
        message(STATUS "Using Qt6 (${Qt6_VERSION})")
    else()
        # Fallback to Qt5
        find_package(Qt5 REQUIRED COMPONENTS Core Widgets Gui)
        set(QT_VERSION_MAJOR 5)
        set(QT_PREFIX Qt5)
        set(QT_FOUND TRUE)
        message(STATUS "Using Qt5 (${Qt5_VERSION}) - fallback")
    endif()
endif()

# Set common variables
set(QT_VERSION ${QT_VERSION_MAJOR})
set(QT_MAJOR_VERSION ${QT_VERSION_MAJOR})

# Final status
if(QT_FOUND)
    message(STATUS "Qt version detected: ${QT_VERSION_MAJOR}")
    message(STATUS "Qt prefix: ${QT_PREFIX}")
else()
    message(FATAL_ERROR "No Qt installation found!")
endif()